name: CI/CD

on:
  pull_request:
    branches: main

jobs:
  cicd:
    name: swift-ci
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - run: swift --version
    - run: xcode-select -p
    - run: sudo xcode-select -s /Applications/Xcode_14.1.app
    - name: swift-ci
      run: swift run --package-path .github/workflows/cicd
