name: CI/CD

on:
  pull_request:
    branches: main

jobs:
  cicd:
    name: swift-ci
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
    - name: versions
      run: |
        swift --version
        xcode-select -p
    - name: swift-ci
      run: swift run --package-path .github/workflows/cicd
